# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
workspace "../Primer.io Debug App.xcworkspace"
project "../Primer.io Debug App.xcodeproj"

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Debug App
  pod 'PrimerSDK', :path => '../../../'

  target 'Debug App Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Debug App UITests' do
    # Pods for testing
  end

end
