name: 'Run Sonar tests'
description: 'Upload code quality scans to Sonar'
inputs:
  github-token:
    description: GitHub token
    required: true
  sonar-token:
    description: Sonar token
    required: true
  sonar-host:
    description: Sonar host URL
    required: true
  coverage-file-names:
    description: Name of the generic coverage file
    required: true
  branch:
    description: Branch
    required: true
  pull-request-number:
    description: PR number
    required: false
  base-branch:
    description: PR target branch
    required: false
  pull-request-sha:
    description: PR commit SHA
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e  #v4.1.7
      with:
        pattern: coverage-file-*
    - name: Install Sonar
      shell: bash
      run: |
        brew install sonar-scanner
    - name: Update sonar-project.properties
      shell: bash
      run: |
        echo "sonar.pullrequest.key=${{ inputs.pull-request-number }}" >> sonar-project.properties
        echo "sonar.pullrequest.branch=${{ inputs.branch }}" >> sonar-project.properties
        echo "sonar.pullrequest.base=${{ inputs.base-branch }}" >> sonar-project.properties
        echo "sonar.scm.revision=${{ inputs.pull-request-sha }}" >> sonar-project.properties
        echo "sonar.coverageReportPaths=${{ inputs.coverage-file-names }}" >> sonar-project.properties
    - name: Run Sonar
      shell: bash
      run: |
        sonar-scanner -Dsonar.token=${{ inputs.sonar-token }}
