use_frameworks!

platform :ios, '10.0'

target 'ExampleApp' do

  pod 'PrimerSDK', :path => '../'
  pod 'Primer3DS'
  pod 'PrimerKlarnaSDK'

 target 'ExampleAppTests' do
   inherit! :search_paths
 end

end
