use_frameworks!

platform :ios, '9.0'

target 'PrimerSDK_Example' do
  pod 'PrimerSDK', :path => '../'

  target 'PrimerSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
