[tool.commitizen]
version_scheme = "semver2"
version = "3.0.0-beta.4"
prerelease_offset = 1
version_files = [
  "Sources/PrimerSDK/Classes/version.swift:let PrimerSDKVersion",
  "*.podspec:s.version"
]
