disabled_rules:
    - superfluous_disable_command

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  
included:
  - Debug App/Sources

excluded:
  - Debug App/Sources/PrimerSDK/Classes/Third Party/PromiseKit
  - Debug App/Pods/**/*
  - Dangerfile.swift
