disabled_rules:
  - superfluous_disable_command
  - type_body_length

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

included:
  - ../Sources

excluded:
  - ../Sources/PrimerSDK/Classes/Third Party/PromiseKit

# Configuration for type names:
# Enforces a minimum length of 3 and a maximum length of 40 characters,
# but excludes the generic type "T".
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - '^T$'

# Configuration for identifier names:
# Enforces a minimum length of 3 and a maximum length of 40 characters,
# excludes "i" and "id", and no longer requires starting lowercase.
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - '^i$'
    - '^id$'
  validates_start_with_lowercase: false
