disabled_rules:
# errors
    - line_length
    - type_body_length
    - function_body_length
    - file_length
    - identifier_name
    - force_try
    - type_name
    - force_cast
    - cyclomatic_complexity
    
# warnings
    - trailing_whitespace
    - unused_optional_binding
    - void_function_in_ternary
    - nesting
    - blanket_disable_command
    - for_where
    - switch_case_alignment
    - unneeded_break_in_switch
    - large_tuple
    - notification_center_detachment
    - deployment_target
    - class_delegate_protocol
    - discouraged_direct_init
    
included:
  - ../Sources
