disabled_rules:
    - superfluous_disable_command
    - type_body_length

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 12
  error: 20
  ignores_case_statements: false

function_parameter_count:
  warning: 6
  error: 8

included:
  - ../Sources

excluded:
  - ../Sources/PrimerSDK/Classes/Third Party/PromiseKit

# Configuration for type names:
# Enforces a minimum length of 3 and a maximum length of 40 characters,
# but excludes the generic type "T" from this rule.
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - '^T$'  # Regex to ignore type name "T"

# Configuration for identifier names:
# Enforces a minimum length of 3 and a maximum length of 40 characters,
# but excludes the loop counter "i" from this rule.
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - '^i$'  # Regex to ignore identifier "i" in for loops
    - '^id$' # Regex to ignore identifier "id"

