disabled_rules:
    - superfluous_disable_command

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  
included:
  - ../Sources

excluded:
  - ../Sources/PrimerSDK/Classes/Third Party/PromiseKit

# Allow single-character generic type 'T' by excluding it from type_name validation.
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - '^T$'  # Regex to ignore type name "T"
