disabled_rules:
  - superfluous_disable_command

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

type_body_length:
  warning: 300 # TODO: Remove this after migrating to Swift 6

included:
  - ../Sources

excluded:
  - ../Sources/PrimerSDK/Classes/Third Party/PromiseKit
