disabled_rules:
    - line_length
    - type_body_length
    - function_body_length
    - file_length
#    - cyclomatic_complexity

included:
  - ../Sources

excluded:
  - ../Sources/PrimerSDK/Classes/Third Party/PromiseKit
