# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
project 'Primer.io Debug App.xcodeproj'
workspace '../PrimerSDK.xcworkspace'

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Debug App
  pod 'PrimerCore', :path => '../'
  pod 'PrimerFoundation', :path => '../'
  pod 'PrimerStepResolver', :path => '../'
  pod 'PrimerBDCEngine', :path => '../'
  pod 'PrimerBDCCore', :path => '../'
  pod 'PrimerNetworking', :path => '../'
  pod 'PrimerResources', :path => '../'
  pod 'PrimerUI', :path => '../'
  pod 'PrimerSDK', :path => '../'
  pod 'Primer3DS'
  pod 'PrimerKlarnaSDK'
  pod 'PrimerIPay88MYSDK'
  pod 'PrimerNolPaySDK'
  pod 'PrimerStripeSDK'
  pod 'IQKeyboardManagerSwift'

  post_install do |installer|
    # Xcode 27 rejects deployment targets below 15.0; some third-party pods still declare lower.
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        if c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
          c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
      end
    end
    fix_code_signing(installer)
  end
end


def fix_code_signing(installer)

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        puts "Fixing code signing for #{target.name}..."
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "N8UN9TR5DY"
        end
      end
    end
  end
end
