# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
project 'Primer.io Debug App.xcodeproj'

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Debug App
  pod 'PrimerSDK', :path => '../'
  pod 'Primer3DS', "~> 2.0.0"
  pod 'PrimerKlarnaSDK'
  pod 'PrimerIPay88MYSDK', :git => 'https://github.com/primer-io/primer-ipay88-sdk-ios.git', :branch => 'master'
  pod 'PrimerNolPaySDK', :git => 'https://github.com/primer-io/primer-nol-pay-sdk-ios.git', :branch => 'nq/swift_version_podspec'
  pod 'IQKeyboardManagerSwift'
  
  target 'Debug App Tests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    fix_code_signing(installer)
    fix_linking(installer)
  end
end


def fix_code_signing(installer)
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        puts "Fixing code signing for #{target.name}..."
        
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "N8UN9TR5DY"
        end
      end
    end
  end
end


def fix_linking(installer)
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.name == "PrimerSDK"
        target.build_configurations.each do |config|
          config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -framework "Primer3DS" -framework "PrimerKlarnaSDK"'
        end
      end
    end
  end
end
