# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
project 'Primer.io Debug App.xcodeproj'

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Debug App
  pod 'PrimerSDK', :path => '../'
  pod 'Primer3DS', :path => '../../primer-sdk-3ds-ios/' #'~> 2.2.0'
  pod 'PrimerKlarnaSDK'
  pod 'PrimerIPay88MYSDK'
  pod 'PrimerNolPaySDK'
  pod 'IQKeyboardManagerSwift'
  
  target 'Debug App Tests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    fix_code_signing(installer)
    fix_linking(installer)
  end
end


def fix_code_signing(installer)
  
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        puts "Fixing code signing for #{target.name}..."
        target.build_configurations.each do |config|
          config.build_settings["DEVELOPMENT_TEAM"] = "N8UN9TR5DY"
        end
      end
    end
  end
end


def fix_linking(installer)
  
  installer.generated_projects.each do |project|
    primer_target_names = project.targets.filter { |target|
      !target.name.start_with?("PrimerSDK") && target.name.start_with?("Primer")
    }.map { |t| "\"#{t.name}\"" }
    project.targets.each do |target|
      if target.name == "PrimerSDK"
        framework_flags = primer_target_names.count > 0 ? "-framework #{primer_target_names.join(' -framework ')}" : ""
        target.build_configurations.each do |config|
          puts "Adding framework flags (#{config.name}): #{framework_flags}"
          other_ldflags = "$(inherited) #{framework_flags}"
          config.build_settings['OTHER_LDFLAGS'] = other_ldflags
        end
      end
    end
  end
end
