//
//  ThemeBuilderDemo.swift
//
//  Copyright © 2026 Primer API Ltd. All rights reserved. 
//  Licensed under the MIT License. See LICENSE file in the project root for full license information.

import PrimerSDK
import SwiftUI

/// Demo for testing theme and layout customizations generated by the interactive docs builders.
/// Paste generated code from:
/// - Design Tokens Explorer → PrimerCheckoutTheme
/// - Card Form Layout Builder → screen replacement / InputFieldConfig
/// - Scope Architecture Explorer → scope customization
@available(iOS 15.0, *)
struct ThemeBuilderDemo: CheckoutComponentsDemo {
    static var metadata: DemoMetadata {
        DemoMetadata(
            name: "Theme Builder",
            description: "Test generated PrimerCheckoutTheme and layout code from the interactive docs builders.",
            tags: ["theme", "layout", "builder", "custom"],
            isCustom: true
        )
    }

    let configuration: DemoConfiguration
    @State private var clientToken: String?
    @State private var error: String?
    @State private var isLoading = true

    var body: some View {
        VStack {
            if isLoading {
                ProgressView("Creating session...")
            } else if let token = clientToken {
                checkoutView(token: token)
            } else if let error {
                Text("Error: \(error)")
                    .foregroundColor(.red)
                    .padding()
            }
        }
        .task { await createSession() }
    }

    // MARK: - Checkout

    @ViewBuilder
    func checkoutView(token: String) -> some View {
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // PASTE GENERATED THEME CODE HERE (from Design Tokens Explorer)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        let theme = PrimerCheckoutTheme(
            colors: ColorOverrides(
                primerColorBrand: Color(red: 0.49, green: 0.36, blue: 0.75)
            ),
            radius: RadiusOverrides(
                primerRadiusMedium: 12
            )
        )

        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        // PASTE GENERATED FIELD STYLING HERE (from Card Form Layout Builder)
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        let fieldStyling = PrimerFieldStyling(
            fontSize: 16,
            borderColor: Color(.separator),
            focusedBorderColor: Color(red: 0.49, green: 0.36, blue: 0.75),
            cornerRadius: 12,
            fieldHeight: 48
        )
        
        PrimerCheckout(
            clientToken: token,
            primerSettings: configuration.settings,
            primerTheme: theme,
            scope: { checkoutScope in
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                // PASTE GENERATED SCOPE CODE HERE
                // (from Card Form Layout Builder / Scope Explorer)
                // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

                // Custom loading screen
                checkoutScope.loadingScreen = {
                    AnyView(
                        VStack(spacing: 16) {
                            ProgressView()
                                .scaleEffect(1.5)
                            Text("Processing payment...")
                                .font(.subheadline)
                                .foregroundColor(.secondary)
                        }
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                    )
                }

                // Custom card form layout (grouped)
                if let cardScope = checkoutScope.getPaymentMethodScope(DefaultCardFormScope.self) {
                    cardScope.screen = { scope in
                        AnyView(
                            VStack(spacing: 16) {
                                scope.PrimerCardNumberField(label: "Card number", styling: fieldStyling)
                                HStack(spacing: 12) {
                                    scope.PrimerExpiryDateField(label: "Expiry", styling: fieldStyling)
                                    scope.PrimerCvvField(label: "CVV", styling: fieldStyling)
                                }
                                scope.PrimerCardholderNameField(label: "Cardholder", styling: fieldStyling)

                                Button("Pay now") {
                                    scope.submit()
                                }
                                .buttonStyle(.borderedProminent)
                                .frame(maxWidth: .infinity)
                            }
                            .padding()
                        )
                    }
                }
            },
            onCompletion: { state in
                switch state {
                case let .success(result):
                    print("[ThemeBuilderDemo] Payment success: \(result)")
                case let .failure(error):
                    print("[ThemeBuilderDemo] Payment failed: \(error.errorId)")
                default:
                    break
                }
            }
        )
    }

    // MARK: - Session

    func createSession() async {
        if let existingToken = configuration.clientToken, !existingToken.isEmpty {
            clientToken = existingToken
            isLoading = false
            return
        }

        guard let clientSession = configuration.clientSession else {
            error = "No session configuration provided - please configure session in main settings"
            isLoading = false
            return
        }

        do {
            clientToken = try await NetworkingUtils.requestClientSession(
                body: clientSession,
                apiVersion: configuration.apiVersion
            )
        } catch {
            self.error = error.localizedDescription
        }
        isLoading = false
    }
}
