# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "My awesome app"
  lane :distribute do
      cocoapods(
        clean_install: true,
        podfile: "./Podfile"
      )

      get_certificates           # invokes cert
      get_provisioning_profile   # invokes sigh

      enable_automatic_code_signing(path: "PrimerSDK.xcodeproj")

      build_app(
        scheme: "PrimerSDK-Example",
        workspace: "./PrimerSDK.xcworkspace"
      )

      firebase_app_distribution(
          app: "1:1024117832450:ios:d8c2e74c66341d8cf3201b",
          testers: "carleriksson92@gmail.com",
          release_notes: "Lots of amazing new features to test out!"
      )

  end
end
