default_platform(:ios)

#----------------------- CONSTANTS -------------------------#

# Appetize
appetize_api_token = ENV['APPETIZE_API_TOKEN']

# Github
github_run_id = ENV["GITHUB_RUN_ID"]
github_run_number = ENV["GITHUB_RUN_NUMBER"]

# Xcode
app_workspace = "Debug App/Primer.io Debug App.xcworkspace"

app_xcode_proj = "Debug App/Primer.io Debug App.xcodeproj"
app_scheme = "Debug App"

spm_app_scheme = "Debug App SPM"
spm_app_xcode_proj = "Debug App/Primer.io Debug App SPM.xcodeproj"

info_plist_path = "Debug App/Info.plist"

# Packages
app_output_path = "/var/tmp/Primer.io_Debug_App.xcarchive/Products/Applications/Debug App.app"
app_output_archive_path = "/var/tmp/Primer.io_Debug_App.xcarchive"

# Utils
sdk_version_name_source_branch = ENV['SOURCE_BRANCH']
source_branch_trimmed = ENV['SOURCE_BRANCH'].gsub("refs/heads/", "")
build_type = ENV['BUILD_TYPE'] || "preview"

podfile_path = "Debug App/Podfile"
pr_number = ENV['PR_NUMBER']

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

#--------------------- END CONSTANTS -----------------------#

#----------------------- FASTLANE -------------------------#

platform :ios do

###################### PUBLIC LANES #######################

  lane :tests do
    run_tests(workspace: app_workspace, 
              scheme: "Debug App Tests",
              destination: "platform=iOS Simulator,name=iPhone 14 Pro",
              xcargs: "EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64",
              skip_package_dependencies_resolution: true)
  end

  lane :ui_tests do
    run_tests(workspace: app_workspace,
              devices: ["iPhone SE", "iPhone 8"])
  end

  lane :danger_check do

    danger(
      danger_id: "check_on_all_prs",
      dangerfile: "Dangerfile",
      github_api_token: ENV["GITHUB_TOKEN"],
      verbose: true,
      remove_previous_comments: true
    )

  end

  lane :qa_release do

    common_pre_build_action

    cocoapods(
      clean_install: true,
      use_bundle_exec: true,
      podfile: podfile_path
    )

    # Build for browserstack
    build_app(
      scheme: app_scheme,
      workspace: app_workspace,
      configuration: "Debug",
      include_bitcode: false,
      export_method: "development",
      xcargs: "-allowProvisioningUpdates"
    )

    # Upload to Browserstack
    upload_to_browserstack_and_save_id(
      file_path: ENV["IPA_OUTPUT_PATH"]
    )

    # Upload to Firebase
    firebase_app_distribution(
      service_credentials_file: "firebase_credentials.json",
      app: "1:1024117832450:ios:d8c2e74c66341d8cf3201b",
      groups: ENV["FIREBASE_COMMA_SEPARATED_TEST_GROUPS"],
      release_notes: "QA release: #{source_branch_trimmed}"
    )

  end

  desc 'This action builds the app using the SPM integration'
  lane :build_spm do
    common_pre_build_action
    build_app(workspace: app_workspace,
              scheme: spm_app_scheme,
              sdk: "iphonesimulator",
              configuration: "Debug",
              destination: "generic/platform=iOS Simulator",
              xcargs: "EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64",
              export_method: "development",
              skip_package_ipa: true,
              skip_package_pkg: true
              )
  end

  lane :build_cocoapods do |options|
    common_pre_build_action

    cocoapods(
      clean_install: true,
      use_bundle_exec: true,
      podfile: podfile_path
    )

    # Run Unit Tests
    if options[:tests]
      tests
    end

    # Build for appetize

    build_app(
      scheme: app_scheme,
      sdk: "iphonesimulator", # Appetize needs a simulator app
      workspace: app_workspace,
      configuration: "Debug",
      destination: "generic/platform=iOS Simulator",
      xcargs: "EXCLUDED_ARCHS[sdk=iphonesimulator*]=arm64",
      include_bitcode: false,
      export_method: "development",
      archive_path: app_output_archive_path,
      # Build speed optimisation
      skip_package_ipa: options[:skip_package_ipa] || true,
      skip_package_pkg: true
    )
  end
  
  desc 'This action runs Unit Tests, builds the app and uploads it to Appetize'
  lane :appetize_build_and_upload do |options|

    build_cocoapods tests: options[:tests] || false

    # Appetize needs the .app to be zipped

    zip_path = "./PrimerSDK_Debug_App.zip"

    zip(
      path: app_output_path,
      output_path: zip_path,
      symlinks: true
    )

    # Find public key of appetize
    # If a build exists with this name, we will overwrite it
    url_end = get_appetize_public_key(build_type, pr_number)
    uri = URI('https://livedemostore.common.primer.io/appetize/ios/' + "#{url_end}")
    public_key = Net::HTTP.get(uri)
    puts "public_key: " + public_key

    # Upload to Appetize
    appetize(
      path: zip_path,
      platform: "ios",
      api_token: appetize_api_token,
      public_key: public_key,
      note: sdk_version_name_source_branch
    )
    
    update_deployment_url(lane_context[SharedValues::APPETIZE_APP_URL])
    update_livedemostore_url("https://livedemostore.common.primer.io/ios/#{url_end}")

  end

  ######################### PRIVATE LANES #########################

  desc 'Common build pre-action'
  private_lane :common_pre_build_action do

    set_version_and_build_number

    setup_signing(
      match_type: "development"
    )

  end

  desc 'This action uploads the .ipa to Browserstack and save its ID into a file'
  private_lane :upload_to_browserstack_and_save_id do |options|

    upload_to_browserstack_app_automate(
      browserstack_username: ENV["BROWSERSTACK_USERNAME"],
      browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
      file_path: options[:file_path]
    )

    save_browserstack_id(browserstack_id: ENV['BROWSERSTACK_APP_ID'])

  end

  desc 'This action creates a temporary keychain and installs certificates and provisioning profiles'
  private_lane :setup_signing do |options|

    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    match(
      type: options[:match_type],
      readonly: true,
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    )

  end

  desc 'This action sets the version and build number'
  lane :set_version_and_build_number do |options|
    # The version number is important only for Appetize
    # The build is identified by the contents of CFBundleVersion in Info.plist

    version_name = get_appetize_public_key(build_type, github_run_id)
    
    set_info_plist_value(path: info_plist_path, key: "CFBundleVersion", value: version_name)
    set_info_plist_value(path: info_plist_path, key: "CFBundleShortVersionString", value: "#{version_name}")
  end

  require 'cocoapods-core'

  private_lane :get_sdk_version do
    file_path = "PrimerSDK.podspec"
    spec = Pod::Specification.from_file(file_path)
    spec.version.to_s
  end

  def get_appetize_public_key(build_type, pr_number)
    case build_type
    when "nightly"
      return "nightly_#{Time.now.strftime("%d.%m.%Y")}"
    when "release"
      return "release_#{get_sdk_version}"
    else
      return "preview_#{pr_number}"
    end
  end
  
  def update_deployment_url(pub_url)
    sh("echo APPETIZE_APP_URL=#{pub_url} >> $GITHUB_ENV")
  end

  def update_livedemostore_url(url)
    sh("echo LIVEDEMOSTORE_URL=#{url} >> $GITHUB_ENV")
  end

  desc 'Store the Browserstack ID into a file'
  private_lane :save_browserstack_id do |options|

    browserstack_id_to_save = options[:browserstack_id]
    browserstack_id_file = "/var/tmp/browserstack_id.txt"

    UI.message("Saving #{browserstack_id_to_save} into #{browserstack_id_file}")

    File.open(browserstack_id_file, 'w') { |file| file.write(options[:browserstack_id]) }

  end

  ################## END PRIVATE LANES ######################

end

#--------------------- END FASTLANE ------------------------#
