//
//  UUIDGenerator.swift
//  PrimerSDK
//
//  Created by CheckoutComponents Analytics
//

import Foundation

/// Helper for generating UUID identifiers for analytics events.
/// Uses standard UUID v4 values generated by Foundation.
struct UUIDGenerator {
    /// Generate a UUID v4 string.
    static func generate() -> String {
        return UUID().uuidString.lowercased()
    }
}
