#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/primer-io/primer-podspecs.git'

target 'HeadlessUniversalCheckoutExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeadlessUniversalCheckoutExample
  pod 'PrimerSDK', :path => '../'
#  pod 'Primer3DS'

end
