name: 'Build and upload to Appetize'
description: 'Build and upload to Appetize'
inputs:
  build_type:
    description: nightly, release, or preview
    required: true
  ssh-private-key:
    description: SSH private key
    required: true
  known-hosts:
    description: Known Hosts
    required: true
  match-password:
    description: Match password
    required: true
  match-git-private-key:
    description: Match git private key
    required: true
  fastlane-password:
    description: Fastlane password
    required: true
  fastlane-session:
    description: Fastlane session
    required: true
  match-keychain-name:
    description: Match keychain name
    required: true
  match-keychain-password:
    description: Match keychain password
    required: true
  appetize-api-token:
    description: Appetize API token
    required: true
  source-branch:
    description: Source branch
    required: true
  github-token:
    description: GitHub token
    required: true
  slack-channel:
    description: Slack channel
    required: true
  slack-reporter-token:
    description: Slack reporter token
    required: true
  github-run-id:
    description: GitHub run ID
    required: true
  pr-number:
    description: PR number
    required: true
runs:
  using: "composite"
  steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh-private-key }}
        name: id_rsa_github_actions
        known_hosts: ${{ inputs.known-hosts }}
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.3.0
    - name: Install SMB
      shell: bash
      run: npm install --save slack-message-builder
    - name: Test, Build, and Distribute app to Appetize 🚀
      shell: bash
      run: |
        bundle exec fastlane appetize_build_and_upload
      env:
        MATCH_PASSWORD: ${{ inputs.match-password }}
        MATCH_GIT_PRIVATE_KEY: ${{ inputs.ssh-private-key }}
        FASTLANE_PASSWORD: ${{ inputs.fastlane-password }}
        FASTLANE_SESSION: ${{ inputs.fastlane-session }}
        MATCH_KEYCHAIN_NAME: ${{ inputs.match-keychain-name }}
        MATCH_KEYCHAIN_PASSWORD: ${{ inputs.match-password }}
        APPETIZE_API_TOKEN: ${{ inputs.appetize-api-token }}
        SOURCE_BRANCH: ${{ inputs.source-branch }}
        BUILD_TYPE: ${{ inputs.build_type }}
        GITHUB_RUN_ID: ${{ inputs.github-run-id }}
        PR_NUMBER: ${{ inputs.pr-number}}
    - uses: peter-evans/find-comment@v2
      if: ${{ success() }}
      id: find_comment
      with:
        issue-number: ${{ inputs.pr-number }}
        body-includes: Appetize link
    - uses: peter-evans/create-or-update-comment@v2
      if: ${{ success() }}
      with:
        body: |
          Appetize link: ${{ env.APPETIZE_APP_URL }}
        edit-mode: replace
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        token: ${{ inputs.github-token }}
    - name: Create Slack Success Summary Report
      if: ${{ success()  }}
      shell: bash
      run: |
        node Report\ Scripts/appetize-success-report-script.js createAppetizeSummaryReport ${{ inputs.source-branch }} ${{ inputs.build_type }}
    - name: Slack Success Notification
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload-file-path: '/var/tmp/appetize-success-link-summary.json'
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-reporter-token }}
    # - name: Create Slack Failure Summary Report
    #   if: ${{ failure() }}
    #   shell: bash
    #   run: |
    #     node Report\ Scripts/appetize-failure-report-script.js createAppetizeSummaryReport ${{ inputs.source-branch }}
    # - name: Slack Notification
    #   if: ${{ failure() }}
    #   uses: slackapi/slack-github-action@v1.23.0
    #   with:
    #     channel-id: ${{ inputs.slack-channel }}
    #     payload-file-path: '/var/tmp/appetize-failure-link-summary.json'
    #   env:
    #     SLACK_BOT_TOKEN: ${{ inputs.slack-reporter-token }}