inputs:
  package-swift:
    description: Package.swift file to use
    required: false

name: 'Run SDK tests'
description: 'Test the SDK using SPM'
runs:
  using: "composite"
  steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '15.2'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 #v2.7.0
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa_github_actions
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677  # v1.172.0
      with:
        ruby-version: "3.2"
        bundler-cache: true
    - name: Setup Package.swift
      if: github.event.inputs.package-swift != ''
      shell: bash
      run: |
        mv Package.swift Package.swift.orig
        cp Package.NolPay.swift Package.swift
    - name: Build SPM App
      shell: bash
      run: |
        bundle exec fastlane test_spm
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
    - name: Archive log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: fastlane-logs
        path: /Users/runner/Library/Logs/scan/PrimerSDKTests.log
        retention-days: 1
    - name: Prepare coverage reports
      shell: bash
      run: |
        bash Scripts/xccov-to-sonarqube-generic.sh fastlane/test_output/PrimerSDKTests.xcresult/ > coverage.xml
        sed "s#$PWD/##g" coverage.xml > sonar-coverage.xml
    - uses: actions/upload-artifact@master
      with:
        name: coverage-file
        path: sonar-coverage.xml
