#if canImport(UIKit)

public enum Currency: String, Codable, CaseIterable {
    case AED
    case AFN
    case ALL
    case AMD
    case ANG
    case AOA
    case ARS
    case AUD
    case AWG
    case AZN
    case BAM
    case BBD
    case BDT
    case BGN
    case BHD
    case BIF
    case BMD
    case BND
    case BOB
    case BRL
    case BSD
    case BTN
    case BWP
    case BYN
    case BZD
    case CAD
    case CDF
    case CHF
    case CKD
    case CLP
    case CNY
    case COP
    case CRC
    case CUC
    case CUP
    case CVE
    case CZK
    case DJF
    case DKK
    case DOP
    case DZD
    case EGP
    case ERN
    case ETB
    case EUR
    case FJD
    case FKP
    case FOK
    case GBP
    case GEL
    case GGP
    case GHS
    case GIP
    case GMD
    case GNF
    case GTQ
    case GYD
    case HKD
    case HNL
    case HRK
    case HTG
    case HUF
    case IDR
    case ILS
    case IMP
    case INR
    case IQD
    case IRR
    case ISK
    case JEP
    case JMD
    case JOD
    case JPY
    case KES
    case KGS
    case KHR
    case KID
    case KMF
    case KPW
    case KRW
    case KWD
    case KYD
    case KZT
    case LAK
    case LBP
    case LKR
    case LRD
    case LSL
    case LYD
    case MAD
    case MDL
    case MGA
    case MKD
    case MMK
    case MNT
    case MOP
    case MRU
    case MUR
    case MVR
    case MWK
    case MXN
    case MYR
    case MZN
    case NAD
    case NGN
    case NIO
    case NOK
    case NPR
    case NZD
    case OMR
    case PAB
    case PEN
    case PGK
    case PHP
    case PKR
    case PLN
    case PND
    case PRB
    case PYG
    case QAR
    case RON
    case RSD
    case RUB
    case RWF
    case SAR
    case SBD
    case SCR
    case SDG
    case SEK
    case SGD
    case SHP
    case SLL
    case SLS
    case SOS
    case SRD
    case SSP
    case STN
    case SYP
    case SZL
    case THB
    case TJS
    case TMT
    case TND
    case TOP
    case TRY
    case TTD
    case TVD
    case TWD
    case TZS
    case UAH
    case UGX
    case USD
    case UYU
    case UZS
    case VES
    case VND
    case VUV
    case WST
    case XAF
    case XCD
    case XOF
    case XPF
    case YER
    case ZAR
    case ZMW
    
    var symbol: String? {
        switch self {
        case .AED:
            return "د.إ"
        case .AFN:
            return "؋"
        case .ALL:
            return "L"
        case .AMD:
            return "֏"
        case .ANG:
            return "ƒ"
        case .AOA:
            return "Kz"
        case .ARS:
            return "$"
        case .AUD:
            return "$"
        case .AWG:
            return "ƒ"
        case .AZN:
            return "₼"
        case .BAM:
            return "KM"
        case .BBD:
            return "$"
        case .BDT:
            return "৳"
        case .BGN:
            return "лв."
        case .BHD:
            return ".د.ب"
        case .BIF:
            return "Fr"
        case .BMD:
            return "$"
        case .BND:
            return "$"
        case .BOB:
            return "Bs."
        case .BRL:
            return "R$"
        case .BSD:
            return "$"
        case .BTN:
            return "Nu."
        case .BWP:
            return "P"
        case .BYN:
            return "Br"
        case .BZD:
            return "$"
        case .CAD:
            return "$"
        case .CDF:
            return "Fr"
        case .CHF:
            return "Fr."
        case .CKD:
            return "$"
        case .CLP:
            return "$"
        case .CNY:
            return "¥"
        case .COP:
            return "$"
        case .CRC:
            return "₡"
        case .CUC:
            return "$"
        case .CUP:
            return "$"
        case .CVE:
            return "$"
        case .CZK:
            return "Kč"
        case .DJF:
            return "Fr"
        case .DKK:
            return "kr."
        case .DOP:
            return "$"
        case .DZD:
            return "د.ج"
        case .EGP:
            return "£"
        case .ERN:
            return "Nfk"
        case .ETB:
            return "Br"
        case .EUR:
            return "€"
        case .FJD:
            return "$"
        case .FKP:
            return "£"
        case .FOK:
            return "kr"
        case .GBP:
            return "£"
        case .GEL:
            return "₾"
        case .GGP:
            return "£"
        case .GHS:
            return "₵"
        case .GIP:
            return "£"
        case .GMD:
            return "D"
        case .GNF:
            return "Fr"
        case .GTQ:
            return "Q"
        case .GYD:
            return "$"
        case .HKD:
            return "$"
        case .HNL:
            return "L"
        case .HRK:
            return "kn"
        case .HTG:
            return "G"
        case .HUF:
            return "Ft"
        case .IDR:
            return "Rp"
        case .ILS:
            return "₪"
        case .IMP:
            return "£"
        case .INR:
            return "₹"
        case .IQD:
            return "ع.د"
        case .IRR:
            return "﷼"
        case .ISK:
            return "kr"
        case .JEP:
            return "£"
        case .JMD:
            return "$"
        case .JOD:
            return "د.ا"
        case .JPY:
            return "¥"
        case .KES:
            return "Sh"
        case .KGS:
            return "с"
        case .KHR:
            return "៛"
        case .KID:
            return "$"
        case .KMF:
            return "Fr"
        case .KPW:
            return "₩"
        case .KRW:
            return "₩"
        case .KWD:
            return "د.ك"
        case .KYD:
            return "$"
        case .KZT:
            return "₸"
        case .LAK:
            return "₭"
        case .LBP:
            return "ل.ل"
        case .LKR:
            return "Rs"
        case .LRD:
            return "$"
        case .LSL:
            return "L"
        case .LYD:
            return "ل.د"
        case .MAD:
            return "د.م."
        case .MDL:
            return "L"
        case .MGA:
            return "Ar"
        case .MKD:
            return "ден"
        case .MMK:
            return "Ks"
        case .MNT:
            return "₮"
        case .MOP:
            return "P"
        case .MRU:
            return "UM"
        case .MUR:
            return "₨"
        case .MVR:
            return ".ރ"
        case .MWK:
            return "MK"
        case .MXN:
            return "$"
        case .MYR:
            return "RM"
        case .MZN:
            return "MT"
        case .NAD:
            return "$"
        case .NGN:
            return "₦"
        case .NIO:
            return "C$"
        case .NOK:
            return "kr"
        case .NPR:
            return "रू"
        case .NZD:
            return "$"
        case .OMR:
            return "ر.ع."
        case .PAB:
            return "B/."
        case .PEN:
            return "S/."
        case .PGK:
            return "K"
        case .PHP:
            return "₱"
        case .PKR:
            return "₨"
        case .PLN:
            return "zł"
        case .PND:
            return "$"
        case .PRB:
            return "р."
        case .PYG:
            return "₲"
        case .QAR:
            return "ر.ق"
        case .RON:
            return "lei"
        case .RSD:
            return "din."
        case .RUB:
            return "₽"
        case .RWF:
            return "Fr"
        case .SAR:
            return "﷼‎"
        case .SBD:
            return "$"
        case .SCR:
            return "₨"
        case .SDG:
            return "ج.س."
        case .SEK:
            return "kr"
        case .SGD:
            return "$"
        case .SHP:
            return "£"
        case .SLL:
            return "Le"
        case .SLS:
            return "Sl"
        case .SOS:
            return "Sh"
        case .SRD:
            return "$"
        case .SSP:
            return "£"
        case .STN:
            return "Db"
        case .SYP:
            return "£"
        case .SZL:
            return "L"
        case .THB:
            return "฿"
        case .TJS:
            return "ЅМ"
        case .TMT:
            return "m"
        case .TND:
            return "د.ت"
        case .TOP:
            return "T$"
        case .TRY:
            return "₺"
        case .TTD:
            return "$"
        case .TVD:
            return "$"
        case .TWD:
            return "$"
        case .TZS:
            return "Sh"
        case .UAH:
            return "₴"
        case .UGX:
            return "Sh"
        case .USD:
            return "$"
        case .UYU:
            return "$"
        case .UZS:
            return "so'm"
        case .VES:
            return "Bs."
        case .VND:
            return "₫"
        case .VUV:
            return "Vt"
        case .WST:
            return "T"
        case .XAF:
            return "Fr"
        case .XCD:
            return "$"
        case .XOF:
            return "Fr"
        case .XPF:
            return "₣"
        case .YER:
            return "ر.ي"
        case .ZAR:
            return "R"
        case .ZMW:
            return "ZK"
        }
    }
    
    var isZeroDecimal: Bool {
        switch self {
        case .JPY, .KRW, .CLP, .VND:
            return true
        default:
            return false
        }
    }
    
}

#endif
