public enum Currency: String, Codable {
    case USD = "USD"
    case GBP = "GBP"
    case EUR = "EUR"
    case SEK = "SEK"
    case NOK = "NOK"
    case DKK = "DKK"
    case JPY = "JPY"
    case AUD = "AUD"
    case CAD = "CAD"
    case CHF = "CHF"
    case CNY = "CNY"
    case HKD = "HKD"
    case NZD = "NZD"
    case KRW = "KRW"
    case SGD = "SGD"
    case MXN = "MXN"
    case INR = "INR"
    case RUB = "RUB"
    case ZAR = "ZAR"
    case TRY = "TRY"
    case BRL = "BRL"
    case TWD = "TWD"
    case PLN = "PLN"
    case THB = "THB"
    case IDR = "IDR"
    case HUF = "HUF"
    case CZK = "CZK"
    case ILS = "ILS"
    case CLP = "CLP"
    case AED = "AED"
    case COP = "COP"
    case SAR = "SAR"
    case MYR = "MYR"
    case RON = "RON"
    case GEL
}
