name: Create Release Candidate

on:
  workflow_dispatch:
    
jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump release version and create changelog"
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
      - name: Create release candidate branch
        run: |
          git checkout -b release-candidate
          git push -u origin release-candidate
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          branch: release-candidate
          prerelease: rc
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.RELEASE_ACCESS_TOKEN }}
          base: master
          branch: release-candidate
          delete-branch: true
          title: Release Candidate ${{ steps.cz.outputs.version }}
          body: ''
