name: Run lint and static analysis

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            relevant:
              - '**/*.swift'
              - '**/*.podspec'

  pod-lint:
    needs: changes
    if: ${{ github.event.pull_request.base.ref == 'master' && needs.changes.outputs.relevant == 'true' }}
    runs-on: macos-26
    name: "Pod lint"
    strategy:
      fail-fast: false
      matrix:
        version: ["5"]

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # v0.13.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1.7.0
        with:
            xcode-version: '26.2'
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b  # v1.321.0
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Lint pod
        run: |
          set -eo pipefail
          pod lib lint PrimerSDK.podspec --allow-warnings --swift-version=${{ matrix.version }} --analyze --include-podspecs='*.podspec'
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
