name: Run lint and static analysis

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pod-lint:
    if: ${{ github.event.pull_request.base.ref == 'master' }}
    runs-on: macos-26
    name: "Pod lint"
    strategy:
      fail-fast: false
      matrix:
        version: ["5"]

    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # v0.13.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90  # v1.7.0
        with:
            xcode-version: '26.2'
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64  # v1.299.0
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Lint pod
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings --swift-version=${{ matrix.version }} --analyze
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
