name: Sonarcloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Update sonar-project.properties
        run: |
          echo "sonar.pullrequest.key=${{github.event.pull_request.number}}" >> sonar-project.properties
          echo "sonar.pullrequest.branch=${{github.head_ref}}" >> sonar-project.properties 
          echo "sonar.pullrequest.base=${{github.base_ref}}" >> sonar-project.properties 
          echo "sonar.scm.revision=${{ github.event.pull_request.head.sha }}" >> sonar-project.properties
          cat sonar-project.properties
      - name: Set up Sonar Quality Gate
        uses: dieuhd/sonar-quality-gate@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GIT_URL: "https://api.github.com"
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: primer-sdk-ios
        with:
          login:  ${{ secrets.SONAR_TOKEN }}
      # - name: SonarCloud Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: https://sonarcloud.io./
      # - name: SonarQube Quality Gate check
      #   id: sonarqube-quality-gate-check
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: https://sonarcloud.io./