# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Debug App
  pod 'PrimerSDK', :path => '../../'
  pod 'Primer3DS'
  pod 'PrimerKlarnaSDK'

  target 'Debug App Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Debug App UITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    fix_code_signing(installer)
  end
  
end

def fix_code_signing(installer)
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["DEVELOPMENT_TEAM"] = "N8UN9TR5DY"
        config.build_settings["GENERATE_INFOPLIST_FILE"] = "YES"
      end
    end
  end
end
