# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Debug App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Debug App
  pod 'PrimerSDK', :path => '../../'
  #  pod 'Primer3DS'
  #  pod 'PrimerKlarnaSDK'
  pod 'PrimerIPay88SDK', :path => '../../../primer-ipay88-sdk-ios'
  
  target 'Debug App Tests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'Debug App UITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.aggregate_targets.each do |target|
      if target.name == "PrimerSDK"
        target.build_configurations.each do |config|
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] = "$(inherited) ${PODS_CONFIGURATION_BUILD_DIR}/PrimerIPay88SDK"
          config.build_settings['LIBRARY_SEARCH_PATHS'] = "$(inherited) ${PODS_CONFIGURATION_BUILD_DIR}/PrimerIPay88SDK"
          config.build_settings['SWIFT_INCLUDE_PATHS'] = "$(inherited) ${PODS_CONFIGURATION_BUILD_DIR}/PrimerIPay88SDK"
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Xcc -fmodule-map-file="${PODS_CONFIGURATION_BUILD_DIR}/PrimerIPay88SDK/PrimerIPay88SDK.modulemap"'
          config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -weak_library -l"PrimerIPay88SDK"'
        end
      end
    end
  end
  
end
